version: "3.8"
services:

  server:
    image: pokevisor-server
    container_name: pokevisor_server
    build:
      context: ../
      dockerfile: ./docker/server.Dockerfile
    ports:
      - "5000:5000"
    networks:
      - back

  frontend:
    image: pokevisor-front
    container_name: pokevisor_front
    build:
      context: ../../web-client/
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - back

networks:
  back:
    driver: bridge