version: "3.8"
services:

  db:
    image: mysql
    container_name: pokevisor_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pokevisor
    ports:
      - "3306:3306"
    networks:
      - back

  server:
    image: pokevisor-server
    container_name: pokevisor_server
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - back
    depends_on:
      - db

  frontend:
    image: pokevisor-front
    container_name: pokevisor_front
    build:
      context: ../../web-client/
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - back

networks:
  back:
    driver: bridge